add_newline = false

command_timeout = 5000

# [line_break]
# disabled = false

format = """$shell$status$character$username$sudo$hostname$directory$all$fill"""

[fill]
symbol = ""

[shell]
disabled = false
bash_indicator = "[ 🐃 ](bg:#f5f5dC)"
fish_indicator = "[ 🐟 ](bg:#f5072c)"
xonsh_indicator = "[ 🐍 ](bg:#f5072c)"
nu_indicator = "[ 🦀 ](bg:#4585f5)"
style = "bg:yellow fg:black"
format = '[ 🐚 ](bg:#595857)[$indicator]($style)'

[character]
disabled = false
success_symbol = "[ ✔ ](bg:green fg:#ffffff)"
error_symbol = "[ ✘ ](bg:red fg:#ffffff)"
format = "$symbol"

[status]
disabled = false
style = "bg:#ffffff fg:#000000 bold"
format = '[ $status ]($style)'

[username]
disabled = false
style_user = "bg:#967969 fg:#000000"
style_root = "bg:red"
show_always = true
format = '[ 👤 ](bg:#595857)[ $user ]($style)'

[hostname]
disabled = false
ssh_only = false
style = "bg:#ccbeaa fg:#000000"
format = "[ 💻 ](bg:#595857 fg:#ffffff)[ $hostname ]($style)"

[directory]
# truncation_length = 5
truncation_symbol = "…"
read_only_style = "197"
style = "fg:#ffffff bg:#bf8484"
format = '[ 🗂️ ](bg:#595857)[$read_only]($read_only_style)[ $path ]($style)'

[directory.substitutions]
"~" = "🛖"
"Documents" = "📄"
"Downloads" = "📥"
"Music" = "🎜"
"Pictures" = "📷"

[sudo]
disabled = false
symbol = " ! "
style = "bg:red fg:#ffffff"
format = "[$symbol]($style)[ sudo ](bg:#ffffff fg:#000000)[ ✔ ](bg:red fg:#ffffff)"


[git_branch]
truncation_length = 20
truncation_symbol = ""
style = "bold green"
format = '[$symbol$branch]($style)'

[git_status]
style = "fg:bold green"
conflicted = "🏳"
up_to_date = "  "
untracked = "  "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "  "
modified = "  "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "
format = '[$all_status$ahead_behind]($style)'

[aws]
# style = ''
format = '[$symbol($profile)(\($region\))($duration)]($style)'

[cmake]
# style = ''
format = '[$symbol($version)]($style)'

[cmd_duration]
# style = ''
format = '[⏱ $duration ]($style)'

[cobol]
# style = ''
format = '[$symbol($version)]($style)'

[conda]
# style = ''
format = '[$symbol$environment]($style)'

[crystal]
# style = ''
format = '[$symbol($version)]($style)'

[dart]
# style = ''
format = '[$symbol($version)]($style)'

[deno]
# style = ''
format = '[$symbol($version)]($style)'

[docker_context]
# style = ''
format = '[$symbol$context]($style)'

[dotnet]
# style = ''
format = '[$symbol($version)(🎯 $tfm)]($style)'

[elixir]
# style = ''
format = '[$symbol($version \(OTP $otp_version\))]($style)'

[elm]
# style = ''
format = '[$symbol($version)]($style)'

[erlang]
# style = ''
format = '[$symbol($version)]($style)'

[gcloud]
# style = ''
format = '[$symbol$account(@$domain)(\($region\))]($style)'

[golang]
# style = ''
format = '[$symbol($version)]($style)'

[helm]
# style = ''
format = '[$symbol($version)]($style)'

[hg_branch]
# style = ''
format = '[$symbol$branch]($style)'

[java]
# style = ''
format = '[$symbol($version)]($style)'

[julia]
# style = ''
format = '[$symbol($version)]($style)'

[kotlin]
# style = ''
format = '[$symbol($version)]($style)'

[kubernetes]
# style = ''
format = '[$symbol$context( \($namespace\))]($style)'

[lua]
# style = ''
format = '[$symbol($version)]($style)'

[memory_usage]
# style = ''
format = '$symbol[$ram( | $swap)]($style)'

[nim]
# style = ''
format = '[$symbol($version)]($style)'

[nix_shell]
# style = ''
format = '[$symbol$state( \($name\))]($style)'

[nodejs]
# style = ''
format = '[$symbol($version)]($style)'

[ocaml]
# style = ''
format = '[$symbol($version)(\($switch_indicator$switch_name\))]($style)'

[openstack]
# style = ''
format = '[$symbol$cloud(\($project\))]($style)'

[package]
# style = ''
format = '[$symbol$version]($style)'

[perl]
# style = ''
format = '[$symbol($version)]($style)'

[php]
# style = ''
format = '[$symbol($version)]($style)'

[pulumi]
# style = ''
format = '[$symbol$stack]($style)'

[purescript]
# style = ''
format = '[$symbol($version)]($style)'

[python]
# style = ''
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

[red]
# style = ''
format = '[$symbol($version)]($style)'

[ruby]
# style = ''
format = '[$symbol($version)]($style)'

[rust]
# style = ''
format = '[$symbol($version)]($style)'

[scala]
# style = ''
format = '[$symbol($version)]($style)'

[swift]
# style = ''
format = '[$symbol($version)]($style)'

[terraform]
# style = ''
format = '[$symbol$workspace]($style)'

[time]
# style = ''
format = '[$time]($style)'

[vagrant]
# style = ''
format = '[$symbol($version)]($style)'

[vlang]
# style = ''
format = '[$symbol($version)]($style)'

[zig]
# style = ''
format = '[$symbol($version)]($style)'
